apiVersion: v1
kind: Secret
metadata:
  name: github-token
  namespace: dev
type: kubernetes.io/dockerconfigjson # ต้องเปลี่ยน type เป็นแบบนี้
data:
  # ค่านี้ได้มาจากการรันคำสั่งด้านล่าง แล้วเอาผลลัพธ์ที่เป็น base64 มาใส่
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7InVzZXJuYW1lIjoiaWFtc2FtaXRkZXYiLCJwYXNzd29yZCI6ImdocF9mNklaM0dFRGVWZ1M2SHpqNTBja1Z6OWZSZ2NoSVQwRnY4R0oiLCJlbWFpbCI6InlvdXItZW1haWxAZXhhbXBsZS5jb20iLCJhdXRoIjoiYVdGdGMyRnRhWFJrWlhZNloyaHdYMlkyU1ZvelIwVkVaVlpuVXpaSWVtbzFNR05yVm5vNVpsSm5ZMmhKVkRCR2RqaEhTZz09In19fQ==